/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const +configH: typeof import('./renderer/+config')['default']
  const Button: typeof import('./components/Button')['Button']
  const Link: typeof import('./components/Link')['Link']
  const PageContextProvider: typeof import('./hooks/usePageContext')['PageContextProvider']
  const PageShell: typeof import('./components/PageShell')['PageShell']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const onRenderClient: typeof import('./renderer/+onRenderClient')['onRenderClient']
  const onRenderHtml: typeof import('./renderer/+onRenderHtml')['onRenderHtml']
  const startTransition: typeof import('react')['startTransition']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const usePageContext: typeof import('./hooks/usePageContext')['usePageContext']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
  const viteConfig: typeof import('./vite')['default']
}
